name: Manage GitHub Team Access

on:
  workflow_dispatch:
    inputs:
      team_name:
        description: 'GitHub Team Name'
        required: true
      repo_names:
        description: 'Comma-separated list of repository names'
        required: true
      permission:
        description: 'Permission level (admin, push, pull)'
        required: true
        default: 'pull'

jobs:
  manage-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Manage GitHub team access to repos
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use PAT stored in GitHub Secrets
      run: |
        python manage_team_access.py "${{ github.event.inputs.team_name }}" "${{ github.event.inputs.repo_names }}" "${{ github.event.inputs.permission }}"
